# Generated by Django 5.1.6 on 2025-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
